const QueryKey = {
    custList: 'customers',
    trkOpList: "trkOps",
    trkTypes: "trkTypes",
    singleCust: "singleCust",
    matTypes: "matTypes",
    singleTrkOpReq: "singleTrkOpReq",
    singleCustReq: "singleCustReq",
    singleTrkOp: "singleTrkOp",
    custReqList: "custReqList",
    trkOpReqList: "trkOpReqList",
    boUser: "boUser",
    singleBo: "singleBo",
    shipmtList: 'shipmtList',
    reqGrp: 'reqGrp',
    grpList: 'grpList',
    notCombGrpReq: "notCombGrpReq",
    shipmtGrp: 'shipmtGrp',
    notCombGrpShipmt: "notCombGrpShipmt",
    custReqByTprId: "custReqByTprId",
    trkOpReqByCusReqId: "trkOpReqByCusReqId",
    allTrks: "allTrks",
    places: "places",
    singleTrk: "singleTrk",
    singleShipmt: "singleShipmt",
    reportConfigList: "reportConfigList",
    shipmtsRepts: "shipmtsRepts",
    logPage: "logPage",
    singleAdrVfy: "singleAdrVfy",
    getAllPenAdrReqs: "getAllPenAdrReqs",
}

export default QueryKey;