const route = {

    saBoLists: "/sa/Backoffices",
    saAddBo: "/sa/AddBackoffice",
    login: '/login',
    editBo: "/sa/EditBackOffice/",
    addUser: "/sa/AddUser",
    editUser: "/sa/EditUser/",
    boInfo: "/sa/BoInfo/",
    userInfo: "/sa/UserInfo/",
    users: "/sa/Users",
    about: "/sa/about",
    editAbout: "/sa/EditAbout",
    priceFactors: "/sa/PriceFactors",
    boDashboard: "/bo/Dashboard",
    boCustList: "/bo/CustList",
    boAddCust: "/bo/AddCust",
    boEditCust: "/bo/EditCust/",
    boCustInfo: "/bo/CustInfo/",
    boTrkOpList: "/bo/TrkOpList/",
    boTrkOpInfo: "/bo/TrkOpInfo/",
    boTrkInfo: "/bo/TrkInfo/",
    boCustReqList: "/bo/CustReqList/",
    boTrkOpReqList: "/bo/TrkOpReqList/",
    boAddCustReq: "/bo/AddCustReq",
    boEditCustReq: "/bo/EditCustReq/",
    boCustReqInfo: "/bo/CustReqInfo/",
    boAddTrkOpReq: "/bo/AddTrkOpReq",
    boEditTrkOpReq: "/bo/EditTrkOpReq/",
    BoUserInfo: "/bo/profile",
    BoStaffInfo: "/bo/staff/",
    BoEditUser: "/bo/EditUser/",
    BoAbout: "/bo/about",
    boShipmtList: "/bo/shipments/",
    boAddShipmt: "/bo/addShipmt",
    boAddTruck: "/bo/addtruck",
    boEditTrk: "/bo/editTruck/",
    boAddTrkOp: "/bo/addTrkOp",
    boEditTrkOp: "/bo/editTrkOp/",
    boShipmtInfo: "/bo/shipmentInfo/",
    boTrkOpReqInfo: "/bo/trkOpReqInfo/",
    saReportConfigs: "/sa/ReportConfigs",
    boReportsList: "/bo/ReportsList",
    saLog: "/sa/LogPage",
    boTrkListByTpPage: "/bo/trucks/",
    boAadhaarRequests: "/bo/aadhaarRequests",
}

export default route;